### ISSUE TITLE
something broke with the libraries?

### ISSUE THREAD

**Issue by x130844** [makertut/esphome-air-sensors#1]
Hi, I don't think the yaml part is correct anymore. 

libraries:
    - Wire
    - https://github.com/makertut/esphome-air-sensors/tree/main/DFRobot_MICS
    - https://github.com/dfrobot/DFRobot_AirQualitySensor

====
It fails with:

Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-3_itlh1a'...
fatal: repository 'https://github.com/makertut/esphome-air-sensors/tree/main/DFRobot_MICS/' not found
VCSBaseException: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/makertut/esphome-air-sensors/tree/main/DFRobot_MICS', '/data/cache/platformio/cache/tmp/pkg-installing-3_itlh1a']:
  File "/usr/local/lib/python3.9/dist-packages/platformio/builder/main.py", line 181:
    env.SConscript("$BUILD_SCRIPT")

**Comment by markwoitaszek** [comment]
you can use the libraries at DFRobot
https://github.com/DFRobot/DFRobot_MICS

**Comment by eishboet** [comment]
change [https://github.com/makertut/esphome-air-sensors/tree/main/DFRobot_MICS](https://github.com/makertut/esphome-air-sensors/tree/main/DFRobot_MICS) to https://github.com/makertut/esphome-air-sensors
